# Generated by Django 4.1.4 on 2023-04-01 20:50

from django.db import migrations, models
import django.utils.timezone
import modules.file_upload_module


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_name', models.CharField(max_length=15, verbose_name='نام اسلایدر')),
                ('slider_title', models.CharField(max_length=15, verbose_name='عنوان اسلایدر')),
                ('slider_short_text', models.CharField(max_length=15, verbose_name='متن کوتاه اسلایدر')),
                ('slider_image', models.FileField(upload_to=modules.file_upload_module.FileUploader.upload_to, verbose_name='عکس اسلایدر')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
