# Generated by Django 4.1.4 on 2023-04-01 21:23

from django.db import migrations, models
import modules.file_upload_module


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_sliderimage_is_active_alter_sliderimage_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='slider_image',
            field=models.FileField(upload_to=modules.file_upload_module.FileUploader.upload_to, verbose_name='عکس اسلایدر'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='slider_short_text',
            field=models.TextField(max_length=15, verbose_name='متن کوتاه اسلایدر'),
        ),
    ]
