# Generated by Django 4.1.4 on 2023-04-22 21:12

from django.db import migrations, models
import modules.file_upload_module


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0004_alter_sliderimage_slider_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sliderimage",
            name="slider_image",
            field=models.FileField(
                upload_to=modules.file_upload_module.FileUploader.upload_to,
                verbose_name="عکس اسلایدر",
            ),
        ),
        migrations.AlterField(
            model_name="sliderimage",
            name="slider_name",
            field=models.CharField(max_length=30, verbose_name="نام اسلایدر"),
        ),
        migrations.AlterField(
            model_name="sliderimage",
            name="slider_short_text",
            field=models.TextField(verbose_name="متن کوتاه اسلایدر"),
        ),
        migrations.AlterField(
            model_name="sliderimage",
            name="slider_title",
            field=models.CharField(max_length=30, verbose_name="عنوان اسلایدر"),
        ),
    ]
