# Generated by Django 4.1.4 on 2023-02-11 19:00

from django.db import migrations, models
import django.utils.timezone
import modules.file_upload_module


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile_number', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('family', models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='ایمیل')),
                ('image', models.ImageField(blank=True, null=True, upload_to=modules.file_upload_module.FileUploader.upload_to, verbose_name='عکس کاربر')),
                ('gender', models.CharField(blank=True, choices=[('man', 'مرد'), ('woman', 'زن')], default='man', max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='ادرس')),
                ('city', models.TextField(blank=True, null=True, verbose_name='شهر')),
                ('province', models.TextField(blank=True, null=True, verbose_name='استان')),
                ('postal_code', models.TextField(blank=True, null=True, verbose_name='کدپستی')),
                ('register_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('active_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
