# Generated by Django 4.1.4 on 2023-03-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('family', models.CharField(max_length=20, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل کاربر')),
                ('topic', models.CharField(max_length=50, verbose_name='موضوع پیام')),
                ('text', models.TextField(verbose_name='متن پیام')),
            ],
        ),
    ]
