# Generated by Django 4.1.4 on 2023-03-29 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusmodel',
            options={'verbose_name': 'نظر عمومی', 'verbose_name_plural': 'نظرات عمومی'},
        ),
        migrations.AddField(
            model_name='contactusmodel',
            name='register_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثیت نظر'),
        ),
    ]
