# Generated by Django 4.1.4 on 2023-05-09 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="تاریخ ویرایش پرداخت"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="register_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ پرداخت"
            ),
        ),
    ]
