# Generated by Django 4.1.4 on 2023-04-22 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "products",
            "0015_alter_brand_brand_image_alter_product_product_image_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeilveryTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_day",
                    models.CharField(max_length=50, verbose_name="زمان ارسال"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="وضعیت روز"),
                ),
            ],
            options={
                "verbose_name": "زمان ارسال",
                "verbose_name_plural": "زمان ارسال",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="تاریخ ثبت سفارش",
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ ویرایش سفارش"
                    ),
                ),
                (
                    "is_finally",
                    models.BooleanField(default=False, verbose_name="نهایی شدن خرید"),
                ),
                (
                    "order_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="کد تولیدی برای سفارش",
                    ),
                ),
                (
                    "discount",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="تخفیف روی فاکتور",
                    ),
                ),
                (
                    "discription",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "delivery_day",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="زمان ارسال"
                    ),
                ),
                (
                    "is_delivered",
                    models.BooleanField(default=False, verbose_name="وضعیت تحویل"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارشات",
            },
        ),
        migrations.CreateModel(
            name="PaymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pyment_title",
                    models.CharField(max_length=100, verbose_name="نوع پرداخت"),
                ),
            ],
            options={
                "verbose_name": "نوع پرداخت",
                "verbose_name_plural": "انواع روش پرداخت",
            },
        ),
        migrations.CreateModel(
            name="OrderDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(default=1, verbose_name="تعداد"),
                ),
                ("price", models.IntegerField(verbose_name="قیمت کالا در فاکتور")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_details",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_details_product",
                        to="products.product",
                        verbose_name="کالا",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_type",
                to="orders.paymenttype",
                verbose_name="روش پرداخت",
            ),
        ),
    ]
