# Generated by Django 4.1.4 on 2023-03-30 21:06

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modules.file_upload_module


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_alter_brand_brand_image_alter_product_product_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='name')),
                ('author_family', models.CharField(max_length=50, verbose_name='family')),
                ('author_slug', models.SlugField(verbose_name='slug')),
                ('author_email', models.EmailField(max_length=255, verbose_name='email')),
                ('author_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='phone')),
                ('auhtor_is_active', models.BooleanField(default=False, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده ها',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('blog_main_image', models.ImageField(upload_to=modules.file_upload_module.FileUploader.upload_to, verbose_name='عکس کاور مقاله')),
                ('blog_slug', models.SlugField(verbose_name='شناسه')),
                ('blog_short_text', models.TextField(verbose_name='متن خلاصه')),
                ('blog_main_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن اصلی')),
                ('blog_register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('blog_publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('blog_update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('blog_is_active', models.BooleanField(default=False, verbose_name='وضعیت مقاله')),
                ('blog_view_number', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('blog_author', models.ManyToManyField(related_name='blog_author', to='blogs.author', verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
            },
        ),
        migrations.CreateModel(
            name='BlogGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=20, verbose_name='title')),
            ],
            options={
                'verbose_name': 'گروه مقاله',
                'verbose_name_plural': 'گروه مقاله',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='کلید واژه')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_tag', to='blogs.blog', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'کلید واژه',
                'verbose_name_plural': 'کلید واژه ها',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments_like', to='blogs.blog', verbose_name='کالا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_user_blog_like', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments_dislike', to='blogs.blog', verbose_name='کالا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_user_blog_dislike', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='CommentBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comment', models.TextField(verbose_name='نظر کاربر')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ درج نظر')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت نظر')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='blogs.blog', verbose_name='کالا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_user_blog', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('user_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_user_blog_comment', to=settings.AUTH_USER_MODEL, verbose_name='ادمین تایید کننده')),
            ],
            options={
                'verbose_name': 'نظر در مورد مقاله ها',
                'verbose_name_plural': 'نظرات در مورد مقاله ها',
            },
        ),
        migrations.CreateModel(
            name='BlogGallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to=modules.file_upload_module.FileUploader.upload_to, verbose_name='عکس مقاله')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_gallary', to='blogs.blog', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'گالری مقاله',
                'verbose_name_plural': 'گالری مقاله',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_group', to='blogs.bloggroup', verbose_name='گروه مقاله'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_related_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_product', to='products.product', verbose_name='کالا مرتبط با مقاله'),
        ),
    ]
