# Generated by Django 4.1.4 on 2023-04-01 20:50

from django.db import migrations, models
import modules.file_upload_module


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dislike',
            options={'verbose_name': 'مقاله های دیس لایک شده', 'verbose_name_plural': 'مقاله های دیس لایک شده'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'مقاله های لایک شده', 'verbose_name_plural': 'مقاله های لایک شده'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_main_image',
            field=models.ImageField(upload_to=modules.file_upload_module.FileUploader.upload_to, verbose_name='عکس کاور مقاله'),
        ),
        migrations.AlterField(
            model_name='bloggallary',
            name='blog_image',
            field=models.ImageField(upload_to=modules.file_upload_module.FileUploader.upload_to, verbose_name='عکس مقاله'),
        ),
    ]
